export const kenzieProjectList = [
    // {
    //     img: null,
    //     isNew: false,
    //     title: null,
    //     kenzie: true,
    //     techList: [
    //     ],
    //     description: null,
    //     finishedAt: null,
    //     linkGithub: null,
    //     publicGithub: false,
    //     linkAppliaction: null,
    //     online: false,
    // },
    {
        img: "burguerKenzie.png",
        isNew: false,
        title: "Burguer Kenzie",
        kenzie: true,
        techList: [
            "React.js",
            "Sass",
            "Html",
        ],
        description: "Projeto em que estudei sobre requisições HTTP no React, e useEffect. Onde simula um site simples de lanchonete.",
        finishedAt: null,
        linkGithub: null,
        publicGithub: false,
        linkAppliaction: "https://react-entrega-s3-template-hamburgueria-willcley.vercel.app",
        online: true,
    },
    {
        img: "controlFinance.png",
        isNew: false,
        title: "Control Finance",
        kenzie: true,
        techList: [
            "Html",
            "Css",
            "Javascript",
        ],
        description: "Projeto feito para praticar o uso de métodos e código limpo, em que aprendi alguns assuntos mais teóricos e de organização. Ele simula um site que calcula transações bancárias.",
        finishedAt: null,
        linkGithub: null,
        publicGithub: false,
        linkAppliaction: "https://kenzie-academy-brasil-developers.github.io/control-finance_willcley/",
        online: true,
    },
    {
        img: "openMusic.png",
        isNew: false,
        title: "Open Music",
        kenzie: true,
        techList: [
            "Html",
            "Css",
            "Javascript",
        ],
        description: "Projeto que simula um site pra comprar musicas. Em que desenvolvi melhor meu conhecimento sobre filtragem de itens e estilizações.",
        finishedAt: null,
        linkGithub: null,
        publicGithub: false,
        linkAppliaction: "https://kenzie-academy-brasil-developers.github.io/open-music-base_willcley/",
        online: true,
    },
    {
        img: "calculadora.png",
        isNew: false,
        title: "Calculadora",
        kenzie: false,
        techList: [
            "Html",
            "Css",
            "Javascript",
        ],
        description: "Projeto de uma calculadora onde estava começando a aprender sobre programação. Desenvolvi ele com a intenção de praticar mais minha lógica e aprender a usar lógica com estilização.",
        finishedAt: null,
        linkGithub: "https://github.com/Willcley/calculadora",
        publicGithub: true,
        linkAppliaction: "https://willcley.github.io/calculadora/",
        online: true,
    },
    // {
    //     img: null,
    //     isNew: false,
    //     title: null,
    //     kenzie: true,
    //     techList: [
    //     ],
    //     description: null,
    //     finishedAt: null,
    //     linkGithub: null,
    //     publicGithub: false,
    //     linkAppliaction: null,
    //     online: false,
    // },
    {
        img: null,
        isNew: false,
        title: "Site Institucional Genérico",
        kenzie: true,
        techList: [
            "Html",
            "Css",
            "Javascript",
        ],
        description: null,
        finishedAt: "26/05/2023",
        linkGithub: "https://github.com/Kenzie-Academy-Brasil-Developers/m2-criando-site-institucional-generico_willcley",
        publicGithub: true,
        linkAppliaction: "https://miniature-adventure-59qv583.pages.github.io",
        online: true,
    },
    {
        img: null,
        isNew: false,
        title: "Lista de Tarefas",
        kenzie: true,
        techList: [
            "Html",
            "Css",
            "Javascript",
        ],
        description: null,
        finishedAt: "11/05/2023",
        linkGithub: "https://github.com/Kenzie-Academy-Brasil-Developers/m1-lista-de-tarefas_willcley",
        publicGithub: true,
        linkAppliaction: "https://reimagined-carnival-l5jllgq.pages.github.io",
        online: true,
    },
];